dependencies:
  - python=3.6
  - astropy=3.0.2
  - coverage
  - cython
  - future
  - ipython
  - sphinx_rtd_theme
  - pip
  - pytest
  - scipy
  - astropy::astroquery
  - chroxvi::radon
  - conda-forge::python-dateutil
  - conda-forge::twine
  - omnia::behave