name: Run unit tests

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 53 3 * * 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      DRAGONS_TEST: $HOME/dragons_tests/

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: http://ssb.stsci.edu/astroconda
          channel-priority: disabled

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install packages
        shell: bash -l {0}
        run: python -m pip install tox tox-conda

      - name: Run Tox
        shell: bash -l {0}
        run: tox -e py37-unit -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
